### ISSUE TITLE
会不会加每日的本子神推荐和魔推荐？

### ISSUE THREAD

**Issue by UnlightedOtaku** [tonquer/picacg-windows#1]
感谢老哥的付出
我试了试用类似的方法去爬推荐但是不成功。。。
url是https://picaapi.picacomic.com/collections
按照老哥的文件自己试了试去爬这个 ，但是返回是{'code': 200, 'message': 'success'}
没有data 经过对比发现signature和app自己生成的不太一样
然后我去看了下 这玩意的算法在so里面 丢进IDA也看不懂。。。

**Comment by tonquer** [comment]
下个版本加入，
signature里面有时间戳，每次生成必然不同
signature的生成可以看看tool.py的__SigFromNative和__ConFromNative函数
是反编译so文件，对照的写的

**Comment by UnlightedOtaku** [comment]
> 下个版本加入，
> signature里面有时间戳，每次生成必然不同
> signature的生成可以看看tool.py的__SigFromNative和__ConFromNative函数
> 是反编译so文件，对照的写的

我仔细看了下 我不小心把data的第二个元素多加了一个"/" 去掉之后获得了正确的响应
