### ISSUE TITLE
not a issue: Arch Linux的支持

### ISSUE THREAD

**Issue by pikakolendo02** [tonquer/picacg-windows#12]
实测在arch下安装了[vulkan-amdgpu-pro](https://aur.archlinux.org/packages/vulkan-amdgpu-pro/)后，waifu2x可以用了，鼓掌！
作者有没有兴趣发布到AUR上呢（手动滑稽）

**Comment by tonquer** [comment]
本项目是用来学习PyQt和Python/C++混编用的，并不打算发布到其他地方

**Comment by pikakolendo02** [comment]
也好，闷声发大财
