### ISSUE TITLE
电脑显示不清晰问题的另一思路

### ISSUE THREAD

**Issue by wswm152** [tonquer/picacg-windows#14]
电脑上图片显示不清晰，有锐化效果的原因可能是由于电脑屏幕dpi较低引起的
排除质量问题，一张1080x1920的图片在电脑上并不能占满整个屏幕，显示的区域可能只有500x800甚至更低
此时需要对图片进行缩放，以匹配显示区域，渲染的程序选用的算法不佳就会导致图片显示效果下降（有些算法是直接马赛克处理的）
如果一味的对图片进行降噪与放大处理，并不能改善图片的显示质量（甚至完全没有用），反而会损耗设备的性能（需要渲染的程序处理的像素点加倍）
故提出建议，使用合理的图片渲染方式（如qt有提供），或选用合适的缩小算法将图片平滑缩小后显示，此类方法不如第一种

个人的一些建议，此类方法不一定会起效，思路源于java swing的Graphics2D抗锯齿处理，仅供参考
ps：我开了waifu2x发现并没有什么改善所以写了此文😂

**Comment by tonquer** [comment]
图片缩小模糊qt是有算法处理的，但是一般都全屏看 故没有用qt做处理
waifu2x在处理黑白和太低分辨率的图片时并没有好的效果

**Comment by wswm152** [comment]
我看上面那个pr使用了平滑处理，能否使用更优的算法进行处理以提高效果呢

**Comment by tonquer** [comment]
> 我看上面那个pr使用了平滑处理，能否使用更优的算法进行处理以提高效果呢

使用了，确实缩放图片后 显示会清晰，下个版本更新就有了

**Comment by zijianjiao2017** [comment]
> > 我看上面那个pr使用了平滑处理，能否使用更优的算法进行处理以提高效果呢
> 
> 使用了，确实缩放图片后 显示会清晰，下个版本更新就有了

但是下载漫画之后使用 macOS 自带的预览程序打开, 颜色会加更鲜艳一点 (更好的观感)
是不是其自动做处理了, 本项目还有优化的空间吧
