### ISSUE TITLE
个人使用的一些问题

### ISSUE THREAD

**Issue by wswm152** [tonquer/picacg-windows#15]
需要添加对使用触控的设备的支持
需要提供32位x86版本的支持
控件不够大的问题（这个还是触控设备的关系，点不到啊）
图片显示定位的问题（能把图片拖走就离谱）
翻页的问题

**Comment by tonquer** [comment]
因为对qt界面设计并不熟悉，所有没有做好界面的设计，起初是想做成uwp应用一样的，如果你有什么界面设置好的应用可以推荐看看
32位并不想做支持，因为还涉及到waifu2x的编译，还有内存限制
设计时并没有考虑触控设备，都是以键鼠为操作逻辑

**Comment by tonquer** [comment]
已经优化了部分，漫画列表可以拖动，看图修改为拖动或点击翻页，应该可以对触控色板兼容

**Comment by zijianjiao2017** [comment]
haoye
