### ISSUE TITLE
显卡占用率过高

### ISSUE THREAD

**Issue by Jackpoint666** [tonquer/picacg-windows#19]
这玩意就是加载个图片（外行话），但是奇了怪的是，我的gtx950存在3d部分过分调用的情况出现，导致显卡负荷过大，如移动光标这样的基本操作出现了可感知的卡顿掉帧，希望原作大大可以修复一下问题，谢谢

**Comment by tonquer** [comment]
请在设置中关闭waifu2x

**Comment by Jackpoint666** [comment]
谢谢，问题已解决

**Comment by Jackpoint666** [comment]
谢谢，问题已解决
