### ISSUE TITLE
代理问题 & 图片显示模式

### ISSUE THREAD

**Issue by xmhwws** [tonquer/picacg-windows#2]
使用最新的v2rayN-Core.zip
https://github.com/2dust/v2rayN/releases
![image](https://user-images.githubusercontent.com/42903751/111806062-8076b780-88c9-11eb-9f13-c19035de28bb.png)

这3个代理选项无论选择哪个
![image](https://user-images.githubusercontent.com/42903751/111806112-91272d80-88c9-11eb-9d5a-4bc8208a59f9.png)
http代理，无论填与不填
![image](https://user-images.githubusercontent.com/42903751/111806255-b61ba080-88c9-11eb-89ea-62369ecc6c3e.png)

picacg都无法正常加载！！！
请教一下作者大大，该如何正常启用代理？（我的梯子正常使用，能访问油管）

2.图片显示模式，能否从正方形改为自适应，正方形看着很别扭

**Comment by tonquer** [comment]
代理请检查是否填写错误
![image](https://user-images.githubusercontent.com/22116659/111809968-7cba5380-8910-11eb-8aab-ca128104104f.png)
![image](https://user-images.githubusercontent.com/22116659/111809921-70ce9180-8910-11eb-8baa-5ebd5b52e1d9.png)
如果填写正确，登录时，v2ray中会看到picacomic域名的路由。
关于图片显示，自适应显示会考虑

**Comment by xmhwws** [comment]
代理填写了，各方面设置没问题

经过测试，才察觉和分流有关
![2021-03-20_20-19-33](https://user-images.githubusercontent.com/42903751/111870303-e6913680-89be-11eb-82f5-779898817e2b.png)


点击测速，分流3的速度最快，我就选择分流3登录，一直提示账号或密码错误；
选择分流2，也是如此；
选择分流1，才正常登陆；

我看测速没问题，以为能正常登陆，哪想到这个提示是错误的

**Comment by tonquer** [comment]
测速使用是图片服务器，哔咔的图片服务器和登录服务器是分开的，不一定能加载图片就一定能登录

**Comment by xmhwws** [comment]
体验了v1.1.0，各方面都很不错，感谢大佬的优秀作品

然而玉中有暇，附上个人的一些小建议（仅供参考）：
1.历史记录增加删除选项，选择性删除一些不喜欢的漫画；
2.图片可以设置原图大小模式，相比放缩到屏幕大小，可能原图大小观看体验更好一些；
3.文字没法复制，比如我看到评论他人推荐，如果里面有日文，只能用OCR识别，再搜索；
4.2个聊天室只能观看聊天消息，无法发送消息；

**Comment by tonquer** [comment]
感谢建议，下版本处理
