### ISSUE TITLE
在macos 10.15.7上程序“显示：应用程序”picacg“无法打开

### ISSUE THREAD

**Issue by 847361092** [tonquer/picacg-windows#21]
同运行一样的系统版本，在解压压缩包bika_v1.1.6_macos-x86_64之后打开app提示应用程序无法打开，请问有什么解决办法吗

**Comment by zijianjiao2017** [comment]
可能是权限问题

**Comment by zijianjiao2017** [comment]
![image](https://user-images.githubusercontent.com/61231083/121486660-eaec4f00-ca03-11eb-9338-4a9d26678ed2.png)
我刚才试了一下去掉权限, 果然打不开了

**Comment by zijianjiao2017** [comment]
你 *cd* 到软件目录下面, 执行
````bash
chmod +x PicACG.app/Contents/MacOS/PicACG
````
试试

**Comment by zijianjiao2017** [comment]
可能是解压缩软件没有设置正确的权限, 等我下次改成 *dmg* 磁盘镜像把

**Comment by zijianjiao2017** [comment]
或者你换个解压软件

**Comment by 847361092** [comment]
我试试

**Comment by 847361092** [comment]
我试试

**Comment by 847361092** [comment]
可以了 已经解决，^_^

**Comment by zijianjiao2017** [comment]
> 同运行一样的系统版本，在解压压缩包bika_v1.1.6_macos-x86_64之后打开app提示应用程序无法打开，请问有什么解决办法吗

其实 v1.1.7 也有 macOS 的, 现在你可以暂时从我的 fork 下载.. [Here](https://github.com/zijianjiao2017/picacg-windows/releases)

**Comment by 847361092** [comment]
> > 同运行一样的系统版本，在解压压缩包bika_v1.1.6_macos-x86_64打开后提示应用程序无法打开，请问有什么解决办法吗
> 
> 其实v1.1.7也有macOS的，现在你可以暂时从我的fork下载..[这里](https://github.com/zijianjiao2017/picacg-windows/releases)

感谢，🙏
