### ISSUE TITLE
求助：聊天室Socket链接上大概一分半后会自动断开，是为什么呢？

### ISSUE THREAD

**Issue by fanyuecheng** [tonquer/picacg-windows#23]
如题：
发送ping正常，但是会在一分半后断开，code1000，是CLOSE_NORMAL | 正常关闭; 无论为何目的而创建, 该链接都已成功完成任务。
想知道你是怎么让它长时间链接的呢？

**Comment by tonquer** [comment]
你是直接使用socket连接吗，需要使用websocket

**Comment by fanyuecheng** [comment]
是websocket 随便找一个在线websocket 试试也这样，会断开
wss://chat-old.wikawika.xyz/socket.io/?EIO=3&transport=websocket     http://coolaf.com/tool/chattest

**Comment by tonquer** [comment]
首先你需要发送登陆消息

**Comment by fanyuecheng** [comment]
我发送的正确吗
42["init",{"gender":"m","exp":200,"slogan":"我是一个小萌新","created_at":"2020-11-02T07:15:12.315Z","verified":false,"_id":"5f9fb200c615dc0fe5788fc0","title":"萌新","avatar":{"path":"a773c9ee-d8b5-424b-af97-5209bc83e733.jpg","originalName":"avatar.jpg","fileServer":"https:\/\/storage1.picacomic.com"},"level":2,"birthday":"2000-11-11T00:00:00.000Z","isPunched":true,"character":"https:\/\/pica-pica.wikawika.xyz\/special\/frame-456.png","email":"ssssseven","name":"我是sssssenven","characters":[]}]

**Comment by tonquer** [comment]
发送登陆消息，
每隔15秒发送ping消息

**Comment by fanyuecheng** [comment]
ping不就是“2” 吗 我也发了 哦 15s 我是25s 我再试试

**Comment by tonquer** [comment]
你发送ping他会回复pong 就是3你有收到吗

**Comment by fanyuecheng** [comment]
[PCSocket webSocket:didReceivePong:]:214 | QMUILogLevelInfo | SOCKET_收到心跳 | 2, {length = 1, bytes = 0x32}
我发的是2 收到的是2

**Comment by tonquer** [comment]
![image](https://user-images.githubusercontent.com/22116659/122149885-5d8b7d80-ce8f-11eb-9386-25818e2b2bbf.png)
按理来说他会回复3

**Comment by tonquer** [comment]
你看看你是不是发送了二进制数据，需要发送字符串数据

**Comment by fanyuecheng** [comment]
是的 我用的三方自带的ping方法 不行 得发送字符串2 可以了 3qqq
