### ISSUE TITLE
关于signature加密方式

### ISSUE THREAD

**Issue by NicetoMiku** [tonquer/picacg-windows#26]
在picacg-windows/src/util/tool.py 下的
`      _src = ToolUtil.__ConFromNative(datas)
       _key = ToolUtil.__SigFromNative()
       signature = ToolUtil.HashKey(_src, _key)
`
中的__ConFromNative和__SigFromNative 我硬是没看懂，请问这个的作用是什么

**Comment by tonquer** [comment]
header的signature字段的生成

**Comment by tonquer** [comment]
就是哔咔的加密验证

**Comment by NicetoMiku** [comment]
谢谢
