### ISSUE TITLE
自动跳转下一章时窗口大小会改变

### ISSUE THREAD

**Issue by misaka19465** [tonquer/picacg-windows#28]
在读上一章时最大化窗口  但自动跳转后回到初始尺寸 而且右上角按钮还是最大化状态  windows

**Comment by zijianjiao2017** [comment]
在 macOS 上, 也有类似的 bug
![image](https://user-images.githubusercontent.com/61231083/124372939-e5132200-dcc0-11eb-9cd7-356ed7ea0c65.png)
![image](https://user-images.githubusercontent.com/61231083/124372943-eba19980-dcc0-11eb-8155-134827b9c3ad.png)

**Comment by zijianjiao2017** [comment]
> 在 macOS 上, 也有类似的 bug
> ![image](https://user-images.githubusercontent.com/61231083/124372939-e5132200-dcc0-11eb-9cd7-356ed7ea0c65.png)
> ![image](https://user-images.githubusercontent.com/61231083/124372943-eba19980-dcc0-11eb-8155-134827b9c3ad.png)

好像触发 bug 之后, 令窗口失去焦点之后恢复焦点就又会好

**Comment by tonquer** [comment]
1.1.9版 调整了最大化直接进入全屏模式，可以试试还有没有问题https://github.com/tonquer/picacg-windows/releases/tag/v1.1.9

**Comment by zijianjiao2017** [comment]
> 1.1.9版 调整了最大化直接进入全屏模式，可以试试还有没有问题https://github.com/tonquer/picacg-windows/releases/tag/v1.1.9

还是有点问题, 我录了一个屏, [Here](https://t.me/s/channel_imfatf1sh/6)

**Comment by misaka19465** [comment]
五小时内解决问题，NB

**Comment by tonquer** [comment]
> > 1.1.9版 调整了最大化直接进入全屏模式，可以试试还有没有问题https://github.com/tonquer/picacg-windows/releases/tag/v1.1.9
> 
> mac 上还是有点问题, 我录了一个屏, [Here](https://t.me/s/channel_imfatf1sh/6)

可能是windows的全屏不适用mac，如果有影响可以先注释掉以下代码
![image](https://user-images.githubusercontent.com/22116659/124380400-0559d580-dcef-11eb-9e91-7ebaecbdc0e7.png)
![image](https://user-images.githubusercontent.com/22116659/124380425-1d315980-dcef-11eb-8828-cc2ac81ab276.png)
![image](https://user-images.githubusercontent.com/22116659/124380448-35a17400-dcef-11eb-85bd-9a58fdbd37c6.png)

**Comment by tonquer** [comment]
1.2.0
