### ISSUE TITLE
鼠标滚轮无效

### ISSUE THREAD

**Issue by misaka19465** [tonquer/picacg-windows#29]
向上滚或向下滚都是这个效果：
![image](https://user-images.githubusercontent.com/45687121/124379751-6384b980-dceb-11eb-873f-dda37cf9b16e.png)

**Comment by tonquer** [comment]
所有漫画都无效吗，上下键有效果吗

**Comment by misaka19465** [comment]
上下键效果相同  所有都不行

**Comment by tonquer** [comment]
我用电脑和笔记本，似乎都没有出现这个问题，暂时不知道是什么情况

**Comment by misaka19465** [comment]
预期效果是上下连在一起  像手机端那样的效果吗

**Comment by tonquer** [comment]
实际是看条漫 向下滚动用的

**Comment by tonquer** [comment]
v1.2.1新增了该效果
