### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by LuzeBillan** [tonquer/picacg-windows#3]
Traceback (most recent call last):
  File "C:\Program Files\PicACG\start.py", line 6, in <module>
    import waifu2x
ImportError: DLL load failed: 找不到指定的模块。

**Comment by LuzeBillan** [comment]
FVESKYBACKUP.DLL
HVSIFILETRUST.DLL
IESHIMS.DLL
NGCRECOVERY.DLL
WFDSCONMGR.DLL
WPAXHOLDER.DLL
检索后排除系统dll发现缺少上述文件

**Comment by tonquer** [comment]
该模块是vs2019编译的，请安装vs运行库环境
并且该模块只支持Python 64位

**Comment by LuzeBillan** [comment]
非常感谢

**Comment by LuzeBillan** [comment]
Vs 2019：
DLL load failed while importing waifu2x: 参数错误。

**Comment by tonquer** [comment]
vs运行库：
https://download.visualstudio.microsoft.com/download/pr/366c0fb9-fe05-4b58-949a-5bc36e50e370/015EDD4E5D36E053B23A01ADB77A2B12444D3FB6ECCEFE23E3A8CD6388616A16/VC_redist.x64.exe
安装这个后还无法导入吗
