### ISSUE TITLE
复制标题多了一些额外内容

### ISSUE THREAD

**Issue by xmhwws** [tonquer/picacg-windows#30]
举个例子：
***********`<font color=#d5577c>(224P)</font><font color=#d5577c>(完)</font>`

很明显，`<font color=#d5577c>(224P)</font><font color=#d5577c>(完)</font>`不是我想要的内容，希望复制时不要复制这部分内容

**Comment by tonquer** [comment]
是有这个问题，后续修复

**Comment by tonquer** [comment]
1.2.0已修复
