### ISSUE TITLE
没有办法保存waifu2x的自定义参数吗

### ISSUE THREAD

**Issue by TralMac** [tonquer/picacg-windows#33]
![QQ截图20210710182940](https://user-images.githubusercontent.com/62429851/125159953-0b4b2d00-e1ad-11eb-9b03-669f5a990eb1.png)
如图，想要看更高分辨率的图的话，只能再单独打开waifu2x进行转换。这样有点麻烦了，可不可以增加自定义waifu2x参数的功能？

**Comment by tonquer** [comment]
可以，后续在设置中开放自定义

**Comment by TralMac** [comment]
> 可以，后续在设置中开放自定义

辛苦啦

**Comment by tonquer** [comment]
1.2.0已新增
