### ISSUE TITLE
深色模式下畫面顯示不正確

### ISSUE THREAD

**Issue by 7Red4** [tonquer/picacg-windows#36]
如題
在深色模式下有些地方的字跟背景一致或顏色相近
以致於難以閱讀

使用的是 MAC 系統設深色模式
可以決定要
- 針對深色模式訂製樣式
- 不設計深色模式 鎖定色票（但覺得這樣不太好

覺得深色模式對眼睛負擔小一點 (´・ω・`)

**Comment by tonquer** [comment]
qt似乎没有这方面的api，我再看看如何实现

**Comment by tonquer** [comment]
深色模式下，部分界面字体看不清已修复

**Comment by 7Red4** [comment]
![image](https://user-images.githubusercontent.com/40208491/126288339-863fd7f2-6cf6-4125-988f-32e378d63a7e.png)
新版 ( v1.2.0 ) 的直接說錯誤打不開 TAT

**Comment by 7Red4** [comment]
補上硬體資訊
![image](https://user-images.githubusercontent.com/40208491/126288600-adaad499-50a9-445e-b562-520b8cb9936e.png)

**Comment by tonquer** [comment]
重新上传了，试试可不可以https://github.com/tonquer/picacg-windows/releases/download/v1.2.0/bika_v1.2.0_mac_x86_x64.dmg

**Comment by 7Red4** [comment]
可以安裝但打開會報錯 就關閉了
(´・ω・`)

**Comment by tonquer** [comment]
你是怎么打开的

**Comment by tonquer** [comment]
是拖动PicACG到/Applications，再到启动器里打开吗

**Comment by 7Red4** [comment]
拖到 /Applications 後
在 finder 打開 /Applications 路徑
右鍵 PicACG 後打開 ( 因為無法驗證的開發者只有這樣才能打開 )
然後如下圖
![image](https://user-images.githubusercontent.com/40208491/126342013-5e566bff-2c85-473e-abe1-b0d341ae5594.png)

**Comment by 7Red4** [comment]
其實看你有已整理好的 api 列表
滿想自己用 electron.js 串一個
或是單純點直接寫網頁版 XD

**Comment by zijianjiao2017** [comment]
> 拖到 /Applications 後
> 在 finder 打開 /Applications 路徑
> 右鍵 PicACG 後打開 ( 因為無法驗證的開發者只有這樣才能打開 )
> 然後如下圖
> ![image](https://user-images.githubusercontent.com/40208491/126342013-5e566bff-2c85-473e-abe1-b0d341ae5594.png)

這是 waifu2x 模块 python 版本错误导致的,
作者第一次打包 macOS 系統的, 之前都是我在打包, 但是最近有點偷懶了, 你可以嘗試一下右鍵「查看包內容」進入contents/macos目錄找到waifu2x.so刪掉再試一次, 缺點就是waifu2x功能會不能用, 但是其他的或許會恢復

**Comment by tonquer** [comment]
> > 拖到 /Applications 後
> > 在 finder 打開 /Applications 路徑
> > 右鍵 PicACG 後打開 ( 因為無法驗證的開發者只有這樣才能打開 )
> > 然後如下圖
> > ![image](https://user-images.githubusercontent.com/40208491/126342013-5e566bff-2c85-473e-abe1-b0d341ae5594.png)
> 
> 這是 waifu2x 模块 python 版本错误导致的,
> 作者第一次打包 macOS 系統的, 之前都是我在打包, 但是最近有點偷懶了, 你可以嘗試一下右鍵「查看包內容」進入contents/macos目錄找到waifu2x.so刪掉再試一次, 缺點就是waifu2x功能會不能用, 但是其他的或許會恢復

嗯 我猜也是waifu2x奔溃导致的

**Comment by 7Red4** [comment]
可以打開了 感謝協助

雖這邊不明顯但我覺得還過得去 🥴

![image](https://user-images.githubusercontent.com/40208491/126349541-cb745a9a-dd7b-4f75-98f6-5e0ef94fffcf.png)
