### ISSUE TITLE
启动时failed to execute script start

### ISSUE THREAD

**Issue by RobinSetsuna** [tonquer/picacg-windows#37]

**Comment by tonquer** [comment]
你的系统是什么

**Comment by RobinSetsuna** [comment]
Edition	Windows 10 Education
Version	21H1
Installed on	‎2020/‎8/‎27
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3920.0


> 你的系统是什么

**Comment by RobinSetsuna** [comment]
本来能顺利进入，但是重开几次后就会报错。

**Comment by tonquer** [comment]
删除config.ini试试，可能是配置读取出错了，后续我在查查问题

**Comment by RobinSetsuna** [comment]
> 删除config.ini试试，可能是配置读取出错了，后续我在查查问题

应该是了，删除后成功进入

**Comment by tonquer** [comment]
v1.2.1已修复
