### ISSUE TITLE
执行生成exe后 启动没有反应

### ISSUE THREAD

**Issue by 635030527** [tonquer/picacg-windows#38]
按照步骤安装了所需的库，生成exe文件 然后进入dist目录执行start.exe文件没有反应

**Comment by tonquer** [comment]
打包后需要把上层的data, models, resources复制到dist目录
参考https://github.com/tonquer/picacg-windows/blob/main/.github/workflows/python-app.yml
也可使用git action编译https://github.com/tonquer/picacg-windows/actions
