### ISSUE TITLE
网络错误，检查代理设置怎么解决

### ISSUE THREAD

**Issue by fgasfasfggg** [tonquer/picacg-windows#39]
要开vpn吗，我开了也没用啊？还是要弄http代理，http代理咋弄呢，小白不懂

**Comment by tonquer** [comment]
如果不使用代理，你可以在设置中取消代理，尝试使用分流2，分流3登陆，
如果使用代理，设置里的http代理填你软件提供的http代理
比如v2ray
![image](https://user-images.githubusercontent.com/22116659/127132376-17023529-7eb9-46f6-b97e-ee6d4493a5cd.png)
