### ISSUE TITLE
关于分类列表的问题

### ISSUE THREAD

**Issue by wesleyx2** [tonquer/picacg-windows#42]
我发现最新版本的无论哪个分类
读取出的漫画总是那第一批
下拉后，读取的还是那一批漫画
看不到更新的漫画
请大佬检查一下~

**Comment by tonquer** [comment]
是有这个问题，搜索界面勾选使用本地数据库时会出现每次都是第一页。你可以去掉这个勾选，暂时使用哔咔的分类搜索

**Comment by tonquer** [comment]
v1.2.2已修复
