### ISSUE TITLE
Windows网络错误

### ISSUE THREAD

**Issue by oxforevero** [tonquer/picacg-windows#43]
不管开没开代理 都是网络错误

**Comment by tonquer** [comment]
不使用代理试试分流2和3，
使用代理你是怎么设置的

**Comment by tonquer** [comment]
> 分流1登不进去，分流2和3可以，但是登进去什么也加载不出来，设置代理：点开setting，勾选代理，并填写地址，保存；不设置的话就不勾选，可以搜索相应的XXX，封面图片可以加载出来，但无法阅读，显示：网络错误，请检查代理设置

你用了代理，分流1也不能用吗

**Comment by tonquer** [comment]
> 分流1登不进去，分流2和3可以，但是登进去什么也加载不出来，设置代理：点开setting，勾选代理，并填写地址，保存；不设置的话就不勾选，可以搜索相应的XXX，封面图片可以加载出来，但无法阅读，显示：网络错误，请检查代理设置

正常来说，登陆成功的话，应该就没问题了，如果可以的话，在设置里把日志等级改为Info，再操作一遍，把logs目录下今天生成的日志文件上传一下，方便查找问题。

**Comment by Steven-hor** [comment]
logs，可以看到吗
[20210819.log](https://github.com/tonquer/picacg-windows/files/7015292/20210819.log)

**Comment by Steven-hor** [comment]
代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来

**Comment by tonquer** [comment]
> 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来

可能和哔咔用的cf cdn有关，不同地区不一样。如果分流2，3不能用，你只能设置代理使用分流1了，

**Comment by Steven-hor** [comment]
> > 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来
> 
> 可能和哔咔用的cf cdn有关，不同地区不一样。如果分流2，3不能用，你只能设置代理使用分流1了，

好吧好吧，感谢解答

**Comment by tonquer** [comment]
> 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来

代理设置需要填翻墙软件提供的http代理地址

> > > 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来
> > 
> > 
> > 可能和哔咔用的cf cdn有关，不同地区不一样。如果分流2，3不能用，你只能设置代理使用分流1了，
> 
> 好吧好吧，感谢解答

代理设置，需要使用翻墙软件提供的http代理地址

**Comment by Steven-hor** [comment]
> > 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来
> 
> 代理设置需要填翻墙软件提供的http代理地址
> 
> > > > 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来
> > > 
> > > 
> > > 可能和哔咔用的cf cdn有关，不同地区不一样。如果分流2，3不能用，你只能设置代理使用分流1了，
> > 
> > 
> > 好吧好吧，感谢解答
> 
> 代理设置，需要使用翻墙软件提供的http代理地址
嗯嗯，用了翻墙代理就可以了，但是翻墙软件比较拉，网速不太行，所以想试试不加代理进分流2或3，应该是地区受限的缘故吧，以前移动热点都可以的，换了位置不行了，再次感谢解答呢

**Comment by tonquer** [comment]
> > 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来
> 
> 代理设置需要填翻墙软件提供的http代理地址
> 
> > > > 代理可能有点问题，所以我是不勾选代理进分流2或3，可以登录进去，但都加载不出来
> > > 
> > > 
> > > 可能和哔咔用的cf cdn有关，不同地区不一样。如果分流2，3不能用，你只能设置代理使用分流1了，
> > 
> > 
> > 好吧好吧，感谢解答
> 
> 代理设置，需要使用翻墙软件提供的http代理地址
> 嗯嗯，用了翻墙代理就可以了，但是翻墙软件比较拉，网速不太行，所以想试试不加代理进分流2或3，应该是地区受限的缘故吧，以前移动热点都可以的，换了位置不行了，再次感谢解答呢

其实哔咔的图片服务器和其他的是分开的，下次再设置里开放，图片不用代理，其他用代理，应该就可以解决图片慢的问题了。

**Comment by tonquer** [comment]
正式版v1.2.3已提交，添加了CDN分流设置
