### ISSUE TITLE
一直提示网络错误

### ISSUE THREAD

**Issue by LonelyPrime** [tonquer/picacg-windows#47]
分流23能登录，但登录了后除了收藏啥也没有，一片空白，收藏里的内容点开就显示网络错误
昨天也有这样的情况，有段时间一直网络错误但过会就好了，今天刚才使用时就一直网络错误

**Comment by tonquer** [comment]
新版本支持了CDN分流，你可以在这里下载beta版本试试
https://github.com/tonquer/picacg-windows/actions/runs/1165538058

如何设置，请看这里
https://github.com/tonquer/picacg-windows/discussions/48

**Comment by LonelyPrime** [comment]
> 新版本支持了CDN分流，你可以在这里下载beta版本试试
> https://github.com/tonquer/picacg-windows/actions/runs/1165538058
> 
> 如何设置，请看这里
> #48

有用

**Comment by tonquer** [comment]
正式版v1.2.3已提交，添加了CDN分流设置
