### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by Weariz** [tonquer/picacg-windows#5]

**Comment by Weariz** [comment]
求大大帮忙看一下这个是什么问题
按照说明解压文件，双击start.exe文件就出现了这个
![image](https://user-images.githubusercontent.com/41582915/113517196-104a8000-95b1-11eb-8977-2eba467ca638.png)
Failed to execute scripy start

**Comment by tonquer** [comment]
请确定你解压正确了，看看是否没有解压models目录
![Uploading image.png…]()

**Comment by tonquer** [comment]
如果还不行，请安装vs运行库再试试
https://download.visualstudio.microsoft.com/download/pr/366c0fb9-fe05-4b58-949a-5bc36e50e370/015EDD4E5D36E053B23A01ADB77A2B12444D3FB6ECCEFE23E3A8CD6388616A16/VC_redist.x64.exe

**Comment by tonquer** [comment]
1.1.3版本修复了这个问题
https://github.com/tonquer/picacg-windows/releases/tag/v1.1.3
