### ISSUE TITLE
请求加入图片按宽度适应

### ISSUE THREAD

**Issue by noir1216** [tonquer/picacg-windows#56]
没有按宽度适应，看WEBTOON太麻烦了，搞得图片一会宽一会细

**Comment by tonquer** [comment]
如果图片比例都不一样，确实会忽大忽小
后面加个选项，统一宽度高度缩放，应该就可以了

**Comment by niuhuan** [comment]
WebToon模式在开发的时候，要注意的地方很多

1. 需要把所有图片从上到下连在一起，不能一张一张翻
2. 图片没有加载完成前要有占位
3. 不能一起加载所有图片，否则会网络拥堵，切换到别的漫画会网速很慢
4. 用户直接跳转翻到后面的图片，前面的图片加载完成，因为图片比占位符高，滚动条应该自动向后滚动，以保证用户看到的图片位置没有变化

**Comment by tonquer** [comment]
> WebToon 模式在开发的时候，要注意的地方很多
> 
> 1. 需要把所有图片从上到下连，不能一张一张翻
> 2. 图片没有加载完成前占位
> 3. 不能加载所有图片，否则会网络拥堵，切换到同样的漫画会网速很慢
> 4. 用户直接跳转到后面的图片，前面的图片加载完成，因为图片比占位符高，滚动条应该自动向后滚动，以保证用户看到的没有变化

感谢提醒

**Comment by tonquer** [comment]
v1.2.6 已支持
