### ISSUE TITLE
新版v1.2.5页面缩放完全出错了

### ISSUE THREAD

**Issue by wesleyx2** [tonquer/picacg-windows#58]
原来的页面就很难用 我1080p屏幕老是显示不完全内容
现在的新版我全屏几乎也没办法看到多少内容 没有图没法形容 
大概就是所有内容都被放大了两倍以上显示了
完全无法正常使用只能回退
大佬你这是在4k 30寸以上显示器开发的？

**Comment by tonquer** [comment]
你设置的是默认模式还是上下滚动的，按理来说默认模式不会超出屏幕大小，是以屏幕分辨率等比缩放的

**Comment by wesleyx2** [comment]
> 你设置的是默认模式还是上下滚动的，按理来说默认模式不会超出屏幕大小，是以屏幕分辨率等比缩放的

我就是默认模式没改设置
就是从登录界面开始就全部双倍缩放了 
进去后所有内容双倍大小 无法显示清楚
完全无法使用
![QQ截图20210914093007](https://user-images.githubusercontent.com/16422807/133181341-080c50d2-d7b7-4aa5-a455-e32e378687c3.jpg)

**Comment by wesleyx2** [comment]
![QQ截图20210914093205](https://user-images.githubusercontent.com/16422807/133181371-d9f73088-4552-413c-a895-c1a731edab74.jpg)
原来git能传图啊 还以为只能文字 大佬看图吧  以上图都是全屏的截图
第二章没有截左边

**Comment by tonquer** [comment]
大概知道了，我在Qt新加了AA_EnableHighDpiScaling标志，他视乎根据dpi自动进行缩放了。我删除一下

**Comment by wesleyx2** [comment]
> 大概知道了，我在Qt新加了AA_EnableHighDpiScaling标志，他视乎根据dpi自动进行缩放了。我删除一下

原来的页面显示能优化一下吗  我这1080p的14寸笔记本显示不了评论回复……
![QQ截图20210914095650](https://user-images.githubusercontent.com/16422807/133182030-52c7be88-0fb9-4edc-b617-cf8c464512be.jpg)

**Comment by tonquer** [comment]
提交了，删除了dpi自适应，在看图模式下，你可以用右键快捷设置模式和缩放。
https://github.com/tonquer/picacg-windows/actions/runs/1231917961

**Comment by tonquer** [comment]
> > 大概知道了，我在Qt新加了AA_EnableHighDpiScaling标志，他视乎根据dpi自动进行缩放了。我删除一下
> 
> 原来的页面显示能优化一下吗 我这1080p的14寸笔记本显示不了评论回复……
> ![QQ截图20210914095650](https://user-images.githubusercontent.com/16422807/133182030-52c7be88-0fb9-4edc-b617-cf8c464512be.jpg)

大部分界面没有考虑全屏使用，我在2k分辨率下还能看，分辨率太低确实太过于拥挤了，有计划会重做这些界面

**Comment by wesleyx2** [comment]
> > > 大概知道了，我在Qt新加了AA_EnableHighDpiScaling标志，他视乎根据dpi自动进行缩放了。我删除一下
> > 
> > 
> > 原来的页面显示能优化一下吗 我这1080p的14寸笔记本显示不了评论回复……
> > ![QQ截图20210914095650](https://user-images.githubusercontent.com/16422807/133182030-52c7be88-0fb9-4edc-b617-cf8c464512be.jpg)
> 
> 大部分界面没有考虑全屏使用，我在2k分辨率下还能看，分辨率太低确实太过于拥挤了，有计划会重做这些界面

修改后新版测试可以正常显示了
期待后面的版本 现在的版本只能说是凑合能用 就是我这种笔记本1080p屏幕用起来很别扭

**Comment by tonquer** [comment]
因为我是做后端的，前端的界面布局着实不懂，都是各种搜索弄得，如果有什么好的界面设计的开源软件，欢迎推荐

**Comment by wesleyx2** [comment]
> 因为我是做后端的，前端的界面布局着实不懂，都是各种搜索弄得，如果有什么好的界面设计的开源软件，欢迎推荐

我也不懂哈哈 不过感觉高度不够用的话 是否可以利用一下宽度
采用双行显示的方法 然后评论在右边显示 这样就不会那么拥挤了
不想看评论的可以点击关闭

**Comment by tonquer** [comment]
> > 因为我是做后端的，前端的界面布局着实不懂，都是各种搜索弄得，如果有什么好的界面设计的开源软件，欢迎推荐
> 
> 我也不懂哈哈 不过感觉高度不够用的话 是否可以利用一下宽度
> 采用双行显示的方法 然后评论在右边显示 这样就不会那么拥挤了
> 不想看评论的可以点击关闭

可以

**Comment by tonquer** [comment]
> > 因为我是做后端的，前端的界面布局着实不懂，都是各种搜索弄得，如果有什么好的界面设计的开源软件，欢迎推荐
> 
> 我也不懂哈哈 不过感觉高度不够用的话 是否可以利用一下宽度
> 采用双行显示的方法 然后评论在右边显示 这样就不会那么拥挤了
> 不想看评论的可以点击关闭

可以

**Comment by niuhuan** [comment]
QT真的是太繁杂了，一起来用FLUTTER鸭，简单的就像JS，如果你不介意软件卓里卓气的话。

**Comment by tonquer** [comment]
> QT真的是太繁杂了，一起来用FLUTTER鸭，简单的就像JS，如果你不介意软件卓里卓气的话。

对js无能为力，qt的quick和qml也是js的写法，但是不懂，没办法

**Comment by tonquer** [comment]
v1.2.6 已经调整了界面
