### ISSUE TITLE
多话数漫画下载问题

### ISSUE THREAD

**Issue by Joke-Ka** [tonquer/picacg-windows#6]
比如《魔都精兵的奴隶》这本，只有打开客户端的第一次获取目录才是完整的，之后无论是下载的获取目录和关掉漫画详情页再打开后的目录都是不完整的且有重复的，导致不能全部话数下载，只能下载部分

**Comment by Joke-Ka** [comment]
目前看貌似超过37话的漫画都有这个问题

**Comment by Joke-Ka** [comment]
可能是pica的获取话数单页40话限制的问题？

**Comment by tonquer** [comment]
因为章节是反序的，代码逻辑写错了，已确认bug

**Comment by tonquer** [comment]
1.1.4已修复该问题
