### ISSUE TITLE
Pica管理組敬啟

### ISSUE THREAD

**Issue by PICAMANGER** [tonquer/picacg-windows#63]
您好，我是PICA管理組，我們最近遇到了非常多的第三方客戶端使用API，以及盜用流量。
這造成了我們在晚高峰流量經常達到峰值。
所以我們在近日展開了對第三方客戶端的排查工作。
我們懇請您理解，PICA作为平台方，每月付出高昂的傳輸成本，用廣告獲得收入維持開銷是正常的行為
您的第三方客戶端去除廣告，這讓我們失去了可以維繫的收入
希望您能封存相關代碼，停止侵犯我們API的行為，我們也在同步向其他github倉庫進行申訴。
非常感謝您的理解，如果需要證明我們PICA開發者的身份，請回復我們，我們會在 工作日 早9：00-晚5點持續跟進，謝謝

**Comment by tonquer** [comment]
该项目只运行在PC端，个人认为与哔咔的安卓端和IOS端并不冲突
