### ISSUE TITLE
无法加载封面

### ISSUE THREAD

**Issue by jcs233** [tonquer/picacg-windows#65]
#62 
[20210925.log](https://github.com/tonquer/picacg-windows/files/7229086/20210925.log)

**Comment by tonquer** [comment]
你是不是把分流设置里的，https关了，打开试试

**Comment by tonquer** [comment]
你是在win10设置中，设置了代理吗

**Comment by tonquer** [comment]
是urllib3版本太高的问题，导致如果使用系统代理无法连接https网站，降级后修复了，可以试试
https://github.com/tonquer/picacg-windows/actions/runs/1272195843

**Comment by jcs233** [comment]
> 是urllib3版本太高的问题，导致如果使用系统代理无法连接https网站，降级后修复了，可以试试
> https://github.com/tonquer/picacg-windows/actions/runs/1272195843
OK了

**Comment by jcs233** [comment]
> > 是urllib3版本太高的问题，导致如果使用系统代理无法连接https网站，降级后修复了，可以试试
> > https://github.com/tonquer/picacg-windows/actions/runs/1272195843

**Comment by jcs233** [comment]
已经可以了

**Comment by tonquer** [comment]
v1.2.6已发布，修复该问题
