### ISSUE TITLE
下载的章节转换失败

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [tonquer/picacg-windows#66]
1.如题 就是转换失败...如果基于waifu2x的话就算了，因为显卡太老根本不支持vulkan
2.下载的漫画咋离线观看？只能打开根目录然后用本地图片查看器打开嘛

**Comment by tonquer** [comment]
转换是基于waifu2x的，不转换也不影响。
目前没有设置离线观看，在线观看会优先读取已下载的不会再重新下载一遍
