### ISSUE TITLE
提问：登录时分流是通过不同url还是proxy区分的？

### ISSUE THREAD

**Issue by HomeArchbishop** [tonquer/picacg-windows#67]
你好。我查阅了大部分开源的api，发现只有一个通用的url，就是picaapi.picacomic.com。我不太清楚分流1/2/3是通过什么方式区分的，是设置代理，还是有不同的url？如果是代理，是否有代理地址。希望告知，谢谢🤧

**Comment by HomeArchbishop** [comment]
试了一下思路应该不错，但是报了错

> FetchError: request to https://picaapi.picacomic.com/auth/sign-in failed, reason: connect ENOENT 104.20.180.50

也就是说这个获得的ip好像不支持ip直接访问。望指教。

**Comment by tonquer** [comment]
方式有多种
可以改系统的hosts
可以用代码里提供的hosts接口，不同语言接口不同
也可以请求 http://104.20.180.50/auth/sign-in， 然后在header中加入header["host"] = picaapi.picacomic.com
