### ISSUE TITLE
waifu2x无法启用，DLL loadfailed：找不到指定的模块

### ISSUE THREAD

**Issue by Weariz** [tonquer/picacg-windows#7]
如图，且文件解压正常
![image](https://user-images.githubusercontent.com/41582915/115272194-b5985300-a170-11eb-979a-39ff2191b583.png)
![image](https://user-images.githubusercontent.com/41582915/115272619-2fc8d780-a171-11eb-921a-bf7480e48da1.png)
同时梯子没有问题，YouTube可以流畅播放4K画质视频，求大佬指点解决，麻烦了，感激不尽

**Comment by Weariz** [comment]
Vs运行库也按照
![image](https://user-images.githubusercontent.com/41582915/115273159-cd240b80-a171-11eb-831a-54cd40972fd6.png)这个安装了
![image](https://user-images.githubusercontent.com/41582915/115273311-f775c900-a171-11eb-86c9-e959c052aa07.png)

**Comment by tonquer** [comment]
你的显卡是啥

**Comment by Weariz** [comment]
![d6050b05d6225378f613fe050f4f2cd](https://user-images.githubusercontent.com/41582915/115330090-fd959500-a1c5-11eb-8f01-f0d5abc1040e.png)
![2f16e5a40704db08e36efa015194631](https://user-images.githubusercontent.com/41582915/115330103-01291c00-a1c6-11eb-8c84-c87dadd6e0f7.png)

**Comment by tonquer** [comment]
C:\Windows\SysWOW64能找到vulkan-1.dll吗
![image](https://user-images.githubusercontent.com/22116659/115334931-d68f9100-a1ce-11eb-9e6b-ed2154663de8.png)

**Comment by tonquer** [comment]
没有vulkan.dll的话，安装vulkan后再试试

**Comment by Weariz** [comment]
好的谢谢，我试试，不好意思麻烦了

tonquer ***@***.***> 于2021年4月20日周二 下午2:13写道：

**Comment by tonquer** [comment]
建议更新显卡驱动，要是没有vulkan-1.dll的话，可能显卡不支持，那是没法用waifu2x的

**Comment by Weariz** [comment]
C盘搜索了一下应该是没有vulkan-1.dl这个文件，我现在安装一下vulkan试一下

tonquer ***@***.***> 于2021年4月20日周二 下午4:24写道：

**Comment by 1823616178** [comment]
我也遇到这个问题

**Comment by tonquer** [comment]
> 我也
> 遇到这个问题AttributeError：模块waifu2x没有属性Init
> 系统是ubuntu桌面

linux的waifu2x还在编译测试中，还不支持，其他功能应该正常

**Comment by tonquer** [comment]
> 我也遇到这个问题
> AttributeError: module 'waifu2x' has no attribute 'Init'
> 系统是ubuntu desktop

1.1.5版本waifu2x支持了linux

**Comment by zijianjiao2017** [comment]
> > 我也遇到这个问题
> > AttributeError: module 'waifu2x' has no attribute 'Init'
> > 系统是ubuntu desktop
> 
> 1.1.5版本waifu2x支持了linux

请问如何从源码编译可在 linux 下使用的 waifu2x Python 模块？

**Comment by tonquer** [comment]
> > > 我也遇到这个问题
> > > AttributeError: module 'waifu2x' has no attribute 'Init'
> > > 系统是ubuntu desktop
> > 
> > 
> > 1.1.5版本waifu2x支持了linux
> 
> 请问如何从源码编译可在 linux 下使用的 waifu2x Python 模块？

你可以先使用lib/waifu2x.so文件，新版本的waifu2x-python代码还在整理，还没有上传

**Comment by zijianjiao2017** [comment]
> > > > 我也遇到这个问题
> > > > AttributeError: module 'waifu2x' has no attribute 'Init'
> > > > 系统是ubuntu desktop
> > > 
> > > 
> > > 1.1.5版本waifu2x支持了linux
> > 
> > 
> > 请问如何从源码编译可在 linux 下使用的 waifu2x Python 模块？
> 
> 你可以先使用lib/waifu2x.so文件，新版本的waifu2x-python代码还在整理，还没有上传

Ok thanks👍🏼
