### ISSUE TITLE
在macos 11.5.2上程序显示：应用程序”picacg“已损坏

### ISSUE THREAD

**Issue by haojunsui** [tonquer/picacg-windows#79]
![image](https://user-images.githubusercontent.com/6809863/138545612-5ea45f67-fd45-461b-bb91-02e38a5aacaf.png)

**Comment by fanyuecheng** [comment]
好像打开了也不行

**Comment by tonquer** [comment]
> 好像打开了也不行

重新上传了，再试试
https://github.com/tonquer/picacg-windows/releases/download/v1.2.8/bika_v1.2.8_macos_x86_64.dmg
