### ISSUE TITLE
请问Waifu2X、为什么会解码失败呢？

### ISSUE THREAD

**Issue by SilentG0** [tonquer/picacg-windows#8]
![微信截图_20210422221520](https://user-images.githubusercontent.com/83020997/115729840-5593ed80-a3b8-11eb-9784-b272a9c1b1ad.png)
如图所示

**Comment by tonquer** [comment]
所有图片都这样吗？

**Comment by SilentG0** [comment]
> 
> 
> 所有图片都这样吗？

是的

**Comment by tonquer** [comment]
你是双显卡吗，如果是，再设置里切换下解码器试试，

**Comment by tonquer** [comment]
你打开这个软件时，有提示waifu2x错误吗
你是双显卡吗，如果是，再设置里切换下解码器试试，
或者选下其他模型试试，
如果都不行的话，因为我也没有这个显卡，所有并不好排查问题

**Comment by SilentG0** [comment]
> 
> 
> 你打开这个软件时，有提示waifu2x错误吗
> 你是双显卡吗，如果是，再设置里切换下解码器试试，
> 或者选下其他模型试试，
> 如果都不行的话，因为我也没有这个显卡，所有并不好排查问题

打开时没报错；是单显卡，无核显；选其他模型也解码错误

**Comment by tonquer** [comment]
好的，后续再添加测试程序打印日志调试一下，

**Comment by SilentG0** [comment]
> 
> 
> 好的，后续再添加测试程序打印日志调试一下，

谢谢，辛苦了

**Comment by tonquer** [comment]
1.1.5版本已发布，看看waifu2x正常不，
不正常请运行debug，把控制台输出复制到文本里上传看看
https://github.com/tonquer/picacg-windows/releases/tag/v1.1.5

**Comment by SilentG0** [comment]
> 
> 
> 1.1.5版本已发布，看看waifu2x正常不，
> 不正常请运行debug，把控制台输出复制到文本里上传看看
> https://github.com/tonquer/picacg-windows/releases/tag/v1.1.5

还是解码失败，附上debug记录
[debug.txt](https://github.com/tonquer/picacg-windows/files/6410215/debug.txt)

**Comment by tonquer** [comment]
看上去像是windows的wincodec库的问题

**Comment by tonquer** [comment]
用这个版本试试，在设置中打开“使用Python转换图片“
https://github.com/tonquer/picacg-windows/releases/download/v1.1.5/bika_v1.1.5.1_windows.zip

**Comment by SilentG0** [comment]
> 
> 
> 用这个版本试试，在设置中打开“使用Python转换图片“
> https://github.com/tonquer/picacg-windows/releases/download/v1.1.5/bika_v1.1.5.1_windows.zip

遗憾，还是失败
[debug2.txt](https://github.com/tonquer/picacg-windows/files/6411440/debug2.txt)

**Comment by tonquer** [comment]
> > 用这个版本试试，在设置中打开“使用Python转换图片“
> > https://github.com/tonquer/picacg-windows/releases/download/v1.1.5/bika_v1.1.5.1_windows.zip
> 
> 遗憾，还是失败
> [debug2.txt](https://github.com/tonquer/picacg-windows/files/6411440/debug2.txt)

看上去 你再设置中没有选择“使用Python转换图片”

**Comment by SilentG0** [comment]
> 
> 
> > > 用这个版本试试，在设置中打开“使用Python转换图片“
> > > https://github.com/tonquer/picacg-windows/releases/download/v1.1.5/bika_v1.1.5.1_windows.zip
> > 
> > 
> > 遗憾，还是失败
> > [debug2.txt](https://github.com/tonquer/picacg-windows/files/6411440/debug2.txt)
> 
> 看上去 你再设置中没有选择“使用Python转换图片”

不好意思，是我的疏忽，勾选后解码成功了
