### ISSUE TITLE
feature request: 保留历史的下载

### ISSUE THREAD

**Issue by FateScript** [tonquer/picacg-windows#83]
安装新版本的时候手贱点了替换，然后以前下载的内容都没了，所以求一个安装时保留历史数据的功能...

另外macos上更新最新版本的app会在退出的时候崩溃（倒是不影响使用

**Comment by tonquer** [comment]
以支持，如果要保留本次的需要在本次更新前，手动将
/Applications/PicACG.app/Contents/Macos/下的
config.ini download.db history.db 复制到~/.picacg目录
