### ISSUE TITLE
多显示器不能保存位置。全屏模式启动不能移动窗口

### ISSUE THREAD

**Issue by heibaiqunhui** [tonquer/picacg-windows#86]
问题1：
多显示器情况下 每次只能在display1启动
无法默认在display2上启动。
问题2“
全屏看书情况下退出后，再次启动程序，退出全屏后不能拖动窗口，只能esc关闭窗口后重新打开才能拖动。

运行环境：
win10 2004
display2竖屏在左，display1横屏在右
     设备ID             主机  左上角   右下角
    \\.\DISPLAY1        是   (0,0)          (1920,1080)
    \\.\DISPLAY2        否   (-1080,0)      (0,1920)

**Comment by tonquer** [comment]
多显示器，貌似是你在哪个显示器下打开，就会显示的那个显示器上。
问题2是有这个问题，目前解决不了，后续将取消默认全屏的功能

**Comment by heibaiqunhui** [comment]
可能是参数不能保存和读取 负坐标 导致每次都在DISPLAY1上显示

**Comment by tonquer** [comment]
已支持
