### ISSUE TITLE
注册

### ISSUE THREAD

**Issue by hahajfs** [tonquer/picacg-windows#87]
新用户注册无限失败？？？？

**Comment by tonquer** [comment]
在设置里设置日志等级为INFO，再注册一遍，把logs目录下的日志上传一下

**Comment by hahajfs** [comment]
显示400
1009
name is already exist

**Comment by hahajfs** [comment]
> 在设置里设置日志等级为INFO，再注册一遍，把logs目录下的日志上传一下

显示400
1009
name is already exist

**Comment by tonquer** [comment]
意思是这个名字已经被注册了

**Comment by hahajfs** [comment]
> 意思是这个名字已经被注册了

输入什么都不行，我把自己名字输进去了都不行🌚🌚

**Comment by tonquer** [comment]
我随便注册了也能成功啊
![image](https://user-images.githubusercontent.com/22116659/142764839-89fd0eb4-b7cf-4300-b8ff-89e9afa537d8.png)

**Comment by hahajfs** [comment]
> 我随便注册了也能成功啊 ![image](https://user-images.githubusercontent.com/22116659/142764839-89fd0eb4-b7cf-4300-b8ff-89e9afa537d8.png)

这就很尴尬，那就肯定是我这边的问题了，
