### ISSUE TITLE
UI文字显示异常

### ISSUE THREAD

**Issue by rihalvnium76** [tonquer/picacg-windows#88]
waifu2x设置文字被压缩到完全看不清，而且也不能拖动侧边高度缩放
![image](https://user-images.githubusercontent.com/57667144/142390696-dd5d072a-f099-47fe-a0f9-3d9606bc5f54.png)

**Comment by tonquer** [comment]
Ui已经做了调整，大概这周末发布

**Comment by tonquer** [comment]
已修复
