### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 847361092** [tonquer/picacg-windows#89]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>启动转换后，转换后的文件夹被放在了bika文件夹的根目录，早先的版本是放在不同名字的下载文件夹同原始版本一起，现在变成了集中放置，由于bika下载点击下载按钮弹出下载框，直接就是【第一话】 所以非常容易出现不同的内容转化后被放在了名叫【第一话】的文件夹乱序放置的情况

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>找到本子下载，同时下载两个【第一话】的本子并且开始转化，这时候转化后的两本会直接放置在同一个文件夹中，并且文件名排序顺序，图片分布是两本内容交错棋盘格分布

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
已修复
