### ISSUE TITLE
[Feature Request] 提供Appimage打包方式

### ISSUE THREAD

**Issue by Brx86** [tonquer/picacg-windows#90]
release直接提供了全部文件的压缩包，但解压后文件比较乱，建议使用appimage打包

**Comment by tonquer** [comment]
可以 不过因为qt库特别大，打包后直接超过300M

**Comment by Brx86** [comment]
我注意到第一次打开后会生成一些文件与文件夹，请问这些配置或缓存文件夹的位置可以修改吗？比如给它们设置环境变量作为保存的位置。如果可以修改的话我会尝试打包到aur。

**Comment by tonquer** [comment]
这些配置的位置将进行调整，后续将不再当前目录生成了

**Comment by Brx86** [comment]
好的谢谢，期待更新
