### ISSUE TITLE
[Feature Request] 希望账户密码不要明文保存在配置文件中

### ISSUE THREAD

**Issue by SeasonG-CN** [tonquer/picacg-windows#91]
### 功能描述
> 希望账户密码不要明文保存在配置文件中

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
似乎没有进行明文保存吧

**Comment by SeasonG-CN** [comment]
> 
我还在使用1.2.1版本,没有更新,新版本已经没有明文保存了吗?没看到改动日志有提到,挠头.jpg
